---
regions:
  - "global"       # Includes IAM, CloudFront, etc.
  - "us-east-1"    # Replace or add regions as needed

blocklist:
  - "7818111xxx"   # Protects production or management account(s)

bypass-alias-check-accounts:
  - "682475224788"   # Your account ID

no-default-blocklist: true  # Allow deleting resources with names like "prod", etc.

accounts:
  "682475224788":
    filters:
      IAMUser:
        - "awsadmin"
      S3Bucket:
        - "dont-delete-rrr"      # Keep specific bucket
      KMSKey:
        - "alias/aws/*"          # Avoid deleting AWS-managed KMS keys

    resource-types:
      includes:
        - "*"   # <--- Wildcard includes ALL supported deletable resources

 
Windows:
 
# Dry Run: Show what would be deleted (but don't actually delete)

aws-nuke run -c config.yaml --no-alias-check --no-dry-run=false

# Export dry run result to a file (stdout only)

aws-nuke run -c config.yaml --no-alias-check --no-dry-run=false | Tee-Object -FilePath "dry-run-output.txt"

# Export full dry run output (stdout + stderr) to a file

aws-nuke run -c config.yaml --no-alias-check --no-dry-run=false *>&1 | Tee-Object -FilePath "dry-run-raw.txt"


#  To actually delete resources (permanent action!)

aws-nuke run -c config.yaml --no-alias-check --no-dry-run *>&1 | Tee-Object -FilePath "nuked-output.txt"



Linux:

# Dry Run: Show what would be deleted (but don't actually delete)
aws-nuke run -c config.yaml --no-alias-check --no-dry-run=false

# Export dry run result to a file (stdout only)
aws-nuke run -c config.yaml --no-alias-check --no-dry-run=false | tee dry-run-output.txt

# Export full dry run output (stdout + stderr) to a file
aws-nuke run -c config.yaml --no-alias-check --no-dry-run=false > >(tee dry-run-raw.txt) 2>&1

#  To actually delete resources (permanent action!)
 aws-nuke run -c config.yaml --no-alias-check --no-dry-run > >(tee nuked-output.txt) 2>&1
